authors:
  myrlund:
    name: Jonas Myrlund
    gravatar: 32738b0ba76006f2f57c3dac162fe87a
    title: "Web developer, beer geek and comp.sci. student"
    twitter: myrlund
    web: http://myrlund.github.com
    about: |
      I'm an averagely nice guy studying comp.sci. at NTNU. I like to play guitar, drink real beer and boss people around.
      
      I spend my days <span title="selling >100k liters of beer per year">running catering operations</span> at 
      [Samfundet](http://samfundet.no), working 
      as a software developer intern at [Comoyo](http://comoyo.com), and 
      filling in my spare time with [various side projects](http://github.com/myrlund).
      
      Sometimes I even study!!!
    